name: Build kernel deb packages
on: push

jobs:
  build:
    name: Build kernel
    runs-on: ubuntu-latest
    container: daze456/deepin-desktop:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: ./build_action.sh

      - name: Artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: ${{ github.workspace }}/artifact/
